app_premises/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path
from .views import camp_list, RealtyDetailView, ReservationFormView, RealtyEditFromView, permission_denied, \
    favorite, add_comment, flat_list, LongTermRealtyDetailView, \
    LonTermRealtyEditFromView, lt_favorite, RegisterObject, create_camp_object_step1, \
    create_camp_object_step2, create_camp_object_step3, create_camp_object_step4, create_camp_object_step5, \
    create_camp_object_step6, create_camp_object_step7, create_camp_object_step8, create_flat_object_step1, \
    create_flat_object_step2, create_flat_object_step3, create_flat_object_step4, create_flat_object_step5, \
    create_flat_object_step6, create_flat_object_step7, create_flat_object_step8

app_name = 'app_premises'

urlpatterns = [
    #  Camp objects block
    path('hotels', camp_list, name='realty_list'),
    path('hotel/<slug:slug>/', RealtyDetailView.as_view(), name='realty_detail'),
    path('hotel/<slug:slug>/edit', RealtyEditFromView.as_view(), name='realty_edit'),
    path('create-camp/1', create_camp_object_step1, name='create_camp1'),
    path('create-camp/2', create_camp_object_step2, name='create_camp2'),
    path('create-camp/3', create_camp_object_step3, name='create_camp3'),
    path('create-camp/4', create_camp_object_step4, name='create_camp4'),
    path('create-camp/5', create_camp_object_step5, name='create_camp5'),
    path('create-camp/6', create_camp_object_step6, name='create_camp6'),
    path('create-camp/7', create_camp_object_step7, name='create_camp7'),
    path('create-camp/8', create_camp_object_step8, name='create_camp8'),
    #  Error pages
    path('error/403', permission_denied, name='403'),
    #  Long term objects block
    path('long/', flat_list, name='flat_list'),
    path('long/<int:pk>/', LongTermRealtyDetailView.as_view(), name='lt_realty_detail'),
    path('long/<int:pk>/edit', LonTermRealtyEditFromView.as_view(), name='lt_realty_edit'),
    path('create-long-term/1', create_flat_object_step1, name='create_flat1'),
    path('create-long-term/2', create_flat_object_step2, name='create_flat2'),
    path('create-long-term/3', create_flat_object_step3, name='create_flat3'),
    path('create-long-term/4', create_flat_object_step4, name='create_flat4'),
    path('create-long-term/5', create_flat_object_step5, name='create_flat5'),
    path('create-long-term/6', create_flat_object_step6, name='create_flat6'),
    path('create-long-term/7', create_flat_object_step7, name='create_flat7'),
    path('create-long-term/8', create_flat_object_step8, name='create_flat8'),
    #  Register realty objects main page
    path('register-object/', RegisterObject.as_view(), name='register_object'),
    #  Reservation page
    path('reservation', ReservationFormView.as_view(), name='reservation'),
    #  AJAX pages
    re_path(r'^favorite/$', favorite, name='favorite'),
    re_path(r'^add_comment/$', add_comment, name='add_comment'),
    re_path(r'^lt_favorite/$', lt_favorite, name='lt_favorite'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

"""Импорт библиотек для Swagger"""
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_version = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_profiler.urls')),
    path('rules/', include('app_rules.urls')),
    path('auto/', include('app_auto.urls')),
    path('rent/', include('app_premises.urls')),
    path('', include('app_index.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_premises/models.py
from uuid import uuid4
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from pytils.translit import slugify
from django.urls import reverse

#  Внешние импорты

from app_data.models import Ip
from app_profiler.models import CustomUser

_REALTY_TYPE = [
    ('h', 'Отель'),
    ('c', 'Хостел'),
    ('a', 'Апартаменты'),
    ('ah', 'Апарт-отель'),
    ('gh', 'Гостевой дом'),
    ('k', 'Коттедж'),
    ('v', 'Вилла'),
    ('kp', 'Кемпинг'),
    ('gp', 'Глэмпинг'),
    ('kv', 'Квартира'),
    ('dm', 'Дом'),
]

_PAY_TYPE = [
    ('o', 'Оплата онлайн'),
    ('c', 'Оплата на месте')
]

_FOOD_OPTIONS = [
    ('a', 'Завтрак включён'),
    ('b', 'Завтрак + обед или ужин включены'),
    ('c', 'Завтрак, обед и ужин включены'),
    ('d', 'Всё включено'),
    ('e', 'Питание не включено'),
]

_BOOK_CANCEL = [
    ('y', 'Беспл. отмена брони'),
    ('n', 'Нет беспл. отмены брони'),
]


def user_directory_path(instance, filename):
    """Путь, куда будет осуществлена загрузка MEDIA_ROOT/<realty_name>/<filename>"""
    return f'{instance}/{filename}'


def advertising_path(instance, filename):
    """Путь, куда будет осуществлена загрузка MEDIA_ROOT/adv/<realty_name>/<filename>"""
    return f'adv/{filename}'


def max_value(image_file):
    """Валидатор для ограничения размера загружаемой картинки"""
    if image_file.size >= 1024 * 1024:
        raise ValueError('Максимальный размер файла 1 Мб')


class RealtyOptions(models.Model):
    option_name = models.CharField(max_length=100, verbose_name='Название опции')
    category = models.CharField(max_length=50, blank=True, verbose_name='Категория')
    icon_url = models.CharField(max_length=100, blank=True, verbose_name='Иконка')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Искали раз')

    def __str__(self):
        return self.option_name

    class Meta:
        # db_table = 'options_db'
        ordering = ['-views_count']
        verbose_name = 'Опция'
        verbose_name_plural = 'Опции'


class FurnitureModel(models.Model):
    name = models.CharField(max_length=40, verbose_name='Название')
    category = models.CharField(max_length=40, verbose_name='Категория')
    icon_url = models.CharField(max_length=100, blank=True, verbose_name='Иконка')

    def __str__(self):
        return self.name

    class Meta:
        """ Определение параметров в мета классе """
        # db_table = 'furniture_db'
        ordering = ['category']
        verbose_name = 'Мебель'
        verbose_name_plural = 'Мебель'


class TechniqueModel(models.Model):
    name = models.CharField(max_length=40, verbose_name='Название')
    category = models.CharField(max_length=40, verbose_name='Категория')
    icon_url = models.CharField(max_length=100, blank=True, verbose_name='Иконка')

    def __str__(self):
        return self.name

    class Meta:
        """ Определение параметров в мета классе """
        # db_table = 'technique_db'
        ordering = ['category']
        verbose_name = 'Техника'
        verbose_name_plural = 'Техника'


class RealtyObjectBaseClass(models.Model):
    company = models.ForeignKey(to=CustomUser, default=1, on_delete=models.CASCADE, verbose_name='Пользователь')
    realty_country = models.CharField(max_length=250, blank=True, verbose_name='Страна')
    realty_region = models.CharField(max_length=250, blank=True, verbose_name='Регион')
    realty_city = models.CharField(max_length=250, blank=True, verbose_name='Населенный пункт')
    realty_address = models.CharField(max_length=250, blank=True, verbose_name='Адрес')
    full_description = models.TextField(max_length=2000, blank=True, verbose_name='Описание')
    realty_price = models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена')
    is_advertised = models.BooleanField(default=False, verbose_name='Статус продвижения')
    views_count = models.ManyToManyField(Ip, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_active = models.BooleanField(default=True, verbose_name='Активно')
    children = models.BooleanField(blank=True, default=False, verbose_name='Можно с детьми')
    animals = models.BooleanField(blank=True, default=False, verbose_name='Можно с животными')
    smoke = models.BooleanField(blank=True, default=False, verbose_name='Можно курить')
    ind = models.CharField(max_length=6, blank=True, verbose_name='Индекс')  # TODO Добавить в админку

    def total_views(self):
        return self.views_count.count()

    class Meta:
        abstract = True
        ordering = ['id']
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'


class Camp(RealtyObjectBaseClass):
    """ Модель альтернативных объектов размещения: кемпинги, глемпинги и прочее """

    _STARS = [
        ('0', 'Нет звезд'),
        ('1', '1 звезда'),
        ('2', '2 звезды'),
        ('3', '3 звезды'),
        ('4', '4 звезды'),
        ('5', '5 звезд'),
    ]

    _REALTY_TYPE = [
        ('k', 'Коттедж'),
        ('kp', 'Кемпинг'),
        ('gp', 'Глэмпинг'),
        ('dm', 'Дом'),
    ]

    realty_name = models.CharField(max_length=100, verbose_name='Название объекта')
    realty_type = models.CharField(max_length=2, blank=True, choices=_REALTY_TYPE, verbose_name='Тип объекта')
    slug = models.SlugField(unique=True, default=None, verbose_name="URL")
    count_of_persons = models.PositiveIntegerField(default=1, verbose_name='Количество спальных мест')
    realty_area = models.PositiveIntegerField(blank=True, default=0, verbose_name='Площадь')
    region_center = models.CharField(max_length=30, blank=True, verbose_name='Региональный центр')
    realty_to_city = models.CharField(max_length=10, blank=True, verbose_name='Расстояние до города')
    book_cancel = models.CharField(max_length=1, choices=_BOOK_CANCEL, default='n', verbose_name='Отмена бронирования')
    pay_type = models.CharField(max_length=1, choices=_PAY_TYPE, default='o', verbose_name='Способ оплаты')
    food_options = models.CharField(max_length=1, choices=_FOOD_OPTIONS, default='e', verbose_name='Опции питания')
    options = models.ManyToManyField(to=RealtyOptions, blank=True, verbose_name='Опции', related_name='option_list')
    arriving_time = models.TimeField(default='14:00', verbose_name='Время заселения с')
    departure_time = models.TimeField(default='09:00', verbose_name='Время выезда с')
    arriving_time_to = models.TimeField(default='23:00', verbose_name='Время заселения до')
    departure_time_to = models.TimeField(default='12:00', verbose_name='Время выезда до')
    realty_book_count = models.PositiveIntegerField(default=0, verbose_name='Бронирований')
    stars = models.CharField(max_length=1, default='0', choices=_STARS,
                             verbose_name='Звёздность')  # TODO Добавить в админку

    def __str__(self):
        return self.realty_name

    def get_absolute_url(self):
        return reverse("realty_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):  # new
        if self.slug is None:
            self.slug = slugify(self.realty_name)
        return super().save(*args, **kwargs)

    class Meta:
        """Определение параметров в мета классе альбом"""
        # db_table = 'camps_db'
        ordering = ['created_at']
        verbose_name = 'Кемпинг'
        verbose_name_plural = 'Кемпинги'


class Flat(RealtyObjectBaseClass):
    _LT_REALTY_TYPE = [
        ('kv', '1-к комнатная квартира'),
        ('2k', '2-х комнатная квартира'),
        ('3k', '3-х комнатная квартира'),
        ('4k', '4-х комнатная квартира'),
        ('ks', 'Квартира-студия'),
        ('a', 'Апартаменты'),
        ('k', 'Коттедж'),
        ('v', 'Вилла'),
        ('dm', 'Дом'),
    ]

    _BATHROOM = [
        ('a', 'Совмещенный'),
        ('b', 'Раздельный'),
    ]

    rooms_count = models.PositiveIntegerField(default=1, blank=True, verbose_name='Количество комнат')
    house_number = models.CharField(max_length=10, blank=True, default='', verbose_name='Номер дома')
    house_korpus = models.CharField(max_length=10, blank=True, default='', verbose_name='Корпус, литер, блок')
    floor = models.PositiveIntegerField(default=1, blank=True, verbose_name='Этаж')
    floor_count = models.PositiveIntegerField(null=True, blank=True, verbose_name='Количество этажей')
    city_area = models.CharField(max_length=50, blank=True, verbose_name='Район города')
    micro_city_area = models.CharField(max_length=50, blank=True, verbose_name='Микрорайон города')
    bathroom = models.CharField(max_length=1, blank=True, choices=_BATHROOM, default='a', verbose_name='Санузел')
    deposit = models.PositiveIntegerField(null=True, blank=True, verbose_name='Залог')
    realty_area = models.FloatField(blank=True, null=True, verbose_name='Площадь')
    realty_type = models.CharField(max_length=2, choices=_LT_REALTY_TYPE, verbose_name='Тип объекта')

    furniture = models.ManyToManyField(to=FurnitureModel,
                                       blank=True,
                                       verbose_name='Мебель',
                                       related_name='furnitures'
                                       )
    technique = models.ManyToManyField(to=TechniqueModel,
                                       blank=True,
                                       verbose_name='Техника',
                                       related_name='techniques'
                                       )

    def __str__(self):
        return str(self.get_realty_type_display()) + ', ' + str(self.realty_area) + ' м²' + ', г. ' + self.realty_city

    class Meta:
        """ Определение параметров в мета классе альбом """
        # db_table = 'flats_db'
        ordering = ['created_at']

templates/app_premises/register_object.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Biglov.ru | Регистрация объекта размещения{% endblock %}</title>
</head>
{% block content %}
<body>
    <div class="register_object__main_container">
        <h2>Добавьте свой объект на Biglov.ru и готовьтесь к наплыву гостей!</h2>
        <h3>Чтобы начать выберите тип объекта, который хотите зарегистрировать на нашем сайте.</h3>
        <div class="register_object__content_container">
            <div class="register_object__menu_container">
                <img class="register_object__main_menu_img" src="{% static 'img/icons/free-icon-hotel-594106.png' %}">
                <div class="register_object__text">
                    Отели, апарт-отели, гостевые дома, хостелы и прочее
                </div>
                <div class="register_object__button_container">
                    <a type="button" class="btn btn-success register_object__register_button" href="{% url 'app_premises:create_flat1' %}" style="pointer-events: none;">Зарегистрировать объект</a>
                </div>
            </div>
            <div class="register_object__menu_container">
                <img class="register_object__main_menu_img" src="{% static 'img/icons/free-icon-apartment-1259768.png' %}">
                <div class="register_object__text">
                    Квартиры, дома и прочее на длительный срок
                </div>
                <div class="register_object__button_container">
                    <a type="button" class="btn btn-success register_object__register_button" href="{% url 'app_premises:create_flat1' %}" style="pointer-events: none;">Зарегистрировать объект</a>
                </div>
            </div>
            <div class="register_object__menu_container">
                <img class="register_object__main_menu_img" src="{% static 'img/icons/free-icon-apartments-382336.png' %}">
                <div class="register_object__text">
                    Варианты размещения с мебелью, кухней и отдельным санузлом, которые сдаются целиком
                </div>
                <div class="register_object__button_container">
                    <a type="button" class="btn btn-success register_object__register_button" href="{% url 'app_premises:create_flat1' %}" style="pointer-events: none;">Зарегистрировать объект</a>
                </div>
            </div>
            <div class="register_object__menu_container">
                <img class="register_object__main_menu_img" src="{% static 'img/icons/free-icon-camping-zone-2387489.png' %}">
                <div class="register_object__text">
                    Глэмпинги, кемпинги, шатры и прочее
                </div>
                <div class="register_object__button_container">
                    <a type="button" class="btn btn-success register_object__register_button" href="{% url 'app_premises:create_camp1' %}">Зарегистрировать объект</a>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}
</html>

templates/app_premises/reservation.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load static %}

{% load humanize %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Страница бронирования</title>
    <link type="text/css" rel="reset" href="../../static/css/reset.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../../static/css/style.css">
    <link type="text/css" rel="stylesheet" href="../../static/css/stylesheet.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

</head>
<body>
{% block content %}
    <div class="reserve-end-container">
        <div class="reserve-img-container">
            <img class="reserve-img" src="../../media/{{ photos.photo }}">
            <div class="reserve__hotel_info">
                <h5 class="end_reserve_form_text">{{ realty_object_to_reserve_page }}</h5>
                <div class="reserve__text_form">{{ realty_object_to_reserve_page.realty_region }}, {{ realty_object_to_reserve_page.realty_city }}, {{ realty_object_to_reserve_page.realty_address }}</div>
                <div class="reserve__text_form">Количество мест: {{ realty_object_to_reserve_page.count_of_persons }}</div>
                <div class="reserve__text_form">Общая площадь помещения: {{ realty_object_to_reserve_page.realty_area }} кв.м.</div>
            </div>
            <div class="reserve__date_range">
                <div>
                    <div>Заезд с {{ realty_object_to_reserve_page.arriving_time }}</div>
                    <div>{{ check_in }}</div>
                </div>
                <div>
                    <div>Выезд до {{ realty_object_to_reserve_page.departure_time }}</div>
                    <div>{{ check_out }}</div>
                </div>
            </div>
        </div>
        <div class="reserve__menu_book_pay_type">
            <div class="reserve__menu_book_pay_type_elem">
                {% if realty_object_to_reserve_page.book_cancel == 'y' %}
                    <li style="color:green; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-calendar-5237130.png">{{ realty_object_to_reserve_page.get_book_cancel_display }}</li>
                {% elif realty_object_to_reserve_page.book_cancel == 'n' %}
                    <li style="color:red; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-calendar-5237130.png">{{ realty_object_to_reserve_page.get_book_cancel_display }}</li>
                {% endif %}
            </div>
            <div class="reserve__menu_book_pay_type_elem_2">
                {% if realty_object_to_reserve_page.food_options == 'a' %}
                    <li style="color:green; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-food-service-4483612.png">{{ realty_object_to_reserve_page.get_food_options_display }}</li>
                {% elif realty_object_to_reserve_page.food_options == 'b' %}
                    <li style="color:green; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-food-service-4483612.png">{{ realty_object_to_reserve_page.get_food_options_display }}</li>
                {% elif realty_object_to_reserve_page.food_options == 'c' %}
                    <li style="color:green; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-food-service-4483612.png">{{ realty_object_to_reserve_page.get_food_options_display }}</li>
                {% elif realty_object_to_reserve_page.food_options == 'd' %}
                    <li style="color:green; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-food-service-4483612.png">{{ realty_object_to_reserve_page.get_food_options_display }}</li>
                {% elif realty_object_to_reserve_page.food_options == 'e' %}
                    <li style="color:red; list-style: none;" class="reserve__main_option_elem"><img class="main_option_img" src="../../static/img/icons/free-icon-food-service-4483612.png">{{ realty_object_to_reserve_page.get_food_options_display }}</li>
                {% endif %}
            </div>
            <div class="reserve__menu_book_pay_type_elem">
                {% if realty_object_to_reserve_page.pay_type == 'o' %}
                    <li class="reserve__pay_type_menu"><img class="reserve__main_option_img" src="../../static/img/icons/free-icon-credit-card-5950249.png">{{ realty_object_to_reserve_page.get_pay_type_display }}</li>
                {% else %}
                    <li class="reserve__pay_type_menu"><img class="reserve__main_option_img" src="../../static/img/icons/money.png">{{ realty_object_to_reserve_page.get_pay_type_display }}</li>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="reserve-end-container2">
        {% if request.user.is_authenticated %}
            <form class="reservation__form_end" method="post">{% csrf_token %}
                <div class="end_reserve_form_text_container">
                    <div class="reserve__main_guest_head_text">Контактные данные гостя</div>
                    <div class="reserve__main_guest_sub_info">Проверьте пожалуйста все поля перед бронированием</div>
                    <div class="reserve__main_guest_name">Имя: {{ current_user.first_name }}</div>
                    <div class="reserve__main_guest_name">Фамилия: {{ current_user.last_name }}</div>
                    <div class="reserve__main_guest_contacts">Номер телефона: {{ current_user.phone }}</div>
                    <div class="reserve__main_guest_contacts">Эл. почта: {{ current_user.email }}</div>
                </div>

                {{ reservation_form.realty.as_hidden }}
                {{ reservation_form.guest.as_hidden }}
                {{ reservation_form.check_in.as_hidden }}
                {{ reservation_form.check_out.as_hidden }}
                {{ reservation_form.is_booked.as_hidden }}
                <div class="total_sum_and_button_reserve_end">
                    {{ reservation_form.total_sum }}<div style="font-size: 1.5em; color: black; font-weight: bold;">₽</div>
                </div>
                <button class="btn btn-light" type="submit" id="end_reserve" name="reservation-submit">Отправить запрос</button>
            </form>
            <div class="reservation_end__info_container">
                <div class="reservation_end__info_block">
                    <h5 style="font-weight: bold;">Как происходит процедура бронирования?</h5>
                    При отправке запроса мы направляем администратору, выбранного Вами объекта, Ваши контактные данные и
                    информацию о бронировании. После получения данных, администратор свяжется с Вами для подтверждения
                    бронирования.
                </div>
                <div class="reservation_end__info_block">
                    <h5 style="font-weight: bold;">Какие данные передаются администратору?</h5>
                    Мы передадим идентификатор объекта, который Вы бронируете, дату заселения, дату отъезда и сумму
                    бронирования.
                    <br>
                    <br>
                    Так же мы передадим Ваш номер телефона и почту, которые Вы использовали при регистрации. Эти данные
                    передаются для того чтобы администратор мог с Вами связаться и подтвердить бронирование. Убедитесь,
                    что Вы имеете доступ к данному номеру и электронной почте, иначе администратор не сможет с Вами
                    связаться и бронирование будет аннулировано.
                </div>
            </div>
        {% elif not request.user.is_authenticated %}
            <!--Форма регистрации для неавторизованного пользователя при попытке бронирования-->
            <form class="reservation__form_end" method="post">{% csrf_token %}
                <form class="register-container">
                    <div class="reserve__register_form_main_container">
                        <div class="reserve__register_form_email_phone">
                            <div class="reserve__register_form_email">{{ reserve_register_form.email }}</div>
                            <div class="reserve__register_form_phone">{{ reserve_register_form.phone }}</div>
                        </div>
                        <div class="reserve__container_register_form_passwords">
                            <div class="reserve__register_form_password">{{ reserve_register_form.password1 }}</div>
                            <div class="reserve__register_form_password">{{ reserve_register_form.password2 }}</div>
                        </div>

                        <div class="reserve__register_form_name_container">
                            <div class="reserve__register_form_name">{{ reserve_register_form.first_name }}</div>
                            <div class="reserve__register_form_last_name">{{ reserve_register_form.last_name }}</div>
                        </div>

                        <div class="reserve__container_for_switch">
                            <div class="form-check form-switch">
                            <p class="register-form-container">
                                <p>{{ reserve_register_form.is_company }}</p>
                                <label class="form-check-label" for="flexSwitchCheckDefault">Являюсь арендодателем</label>
                            </div>
                            <div class="form-check form-switch">
                                {{ reserve_register_form.is_active }}
                                <label class="form-check-label" for="flexSwitchCheckDefault">Согласиться с <a style="color: blue;" data-bs-toggle="modal" data-bs-target="#staticBackdropRules">правилами сайта</a></label>
                            </div>
                            <button type="submit" name="reserve__register_form_submit" class="btn btn-light" id="reserve__register_button">Зарегистрироваться</button>
                        </div>
                    </div>

                </form>
                <div class="reserve__total_sum_and_submit">
                    <div class="total_sum_and_button_reserve_end">
                        {{ reservation_form.total_sum }}<div style="font-size: 1.5em; color: black; font-weight: bold;">₽</div>
                    </div>
                    <button class="btn btn-light" type="submit" id="end_reserve_not_auth" name="reservation-submit" disabled>Подтвердить</button>
                </div>

            </form>

            <!-- Modal правила -->
            <div class="modal fade" id="staticBackdropRules" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    ...
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Understood</button>
                  </div>
                </div>
              </div>
            </div>

        {% endif %}
    </div>
{% endblock content %}
</body>

</html>