app_auto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import auto_index_page
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'app_auto'

urlpatterns = [
    path('', auto_index_page, name='auto_index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_index/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import index_page
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'app_index'

urlpatterns = [
    path('', index_page, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_premises/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path
from .views import camp_list, RealtyDetailView, ReservationFormView, RealtyEditFromView, permission_denied, \
    favorite, add_comment, flat_list, LongTermRealtyDetailView, \
    LonTermRealtyEditFromView, lt_favorite, RegisterObject, create_camp_object_step1, \
    create_camp_object_step2, create_camp_object_step3, create_camp_object_step4, create_camp_object_step5, \
    create_camp_object_step6, create_camp_object_step7, create_camp_object_step8, create_flat_object_step1, \
    create_flat_object_step2, create_flat_object_step3, create_flat_object_step4, create_flat_object_step5, \
    create_flat_object_step6, create_flat_object_step7, create_flat_object_step8

app_name = 'app_premises'

urlpatterns = [
    #  Camp objects block
    path('hotels', camp_list, name='realty_list'),
    path('hotel/<slug:slug>/', RealtyDetailView.as_view(), name='realty_detail'),
    path('hotel/<slug:slug>/edit', RealtyEditFromView.as_view(), name='realty_edit'),
    path('create-camp/1', create_camp_object_step1, name='create_camp1'),
    path('create-camp/2', create_camp_object_step2, name='create_camp2'),
    path('create-camp/3', create_camp_object_step3, name='create_camp3'),
    path('create-camp/4', create_camp_object_step4, name='create_camp4'),
    path('create-camp/5', create_camp_object_step5, name='create_camp5'),
    path('create-camp/6', create_camp_object_step6, name='create_camp6'),
    path('create-camp/7', create_camp_object_step7, name='create_camp7'),
    path('create-camp/8', create_camp_object_step8, name='create_camp8'),
    #  Error pages
    path('error/403', permission_denied, name='403'),
    #  Long term objects block
    path('long/', flat_list, name='flat_list'),
    path('long/<int:pk>/', LongTermRealtyDetailView.as_view(), name='lt_realty_detail'),
    path('long/<int:pk>/edit', LonTermRealtyEditFromView.as_view(), name='lt_realty_edit'),
    path('create-long-term/1', create_flat_object_step1, name='create_flat1'),
    path('create-long-term/2', create_flat_object_step2, name='create_flat2'),
    path('create-long-term/3', create_flat_object_step3, name='create_flat3'),
    path('create-long-term/4', create_flat_object_step4, name='create_flat4'),
    path('create-long-term/5', create_flat_object_step5, name='create_flat5'),
    path('create-long-term/6', create_flat_object_step6, name='create_flat6'),
    path('create-long-term/7', create_flat_object_step7, name='create_flat7'),
    path('create-long-term/8', create_flat_object_step8, name='create_flat8'),
    #  Register realty objects main page
    path('register-object/', RegisterObject.as_view(), name='register_object'),
    #  Reservation page
    path('reservation', ReservationFormView.as_view(), name='reservation'),
    #  AJAX pages
    re_path(r'^favorite/$', favorite, name='favorite'),
    re_path(r'^add_comment/$', add_comment, name='add_comment'),
    re_path(r'^lt_favorite/$', lt_favorite, name='lt_favorite'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_rules/urls.py
from django.conf import settings
from django.urls import path
from .views import our_values_page, rules_page, privacy_policy_page
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app_rules'

urlpatterns = [
    path('values', our_values_page, name='our_values'),
    path('regulations', rules_page, name='rules'),
    path('privacy', privacy_policy_page, name='privacy_policy'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

"""Импорт библиотек для Swagger"""
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_version = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_profiler.urls')),
    path('rules/', include('app_rules.urls')),
    path('auto/', include('app_auto.urls')),
    path('rent/', include('app_premises.urls')),
    path('', include('app_index.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}Biglov{% endblock title%}</title>
    <link type="text/css" rel="reset" href="{% static 'css/reset.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <script src="../../static/js/datepicker.ru-RU.js"></script>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>

</head>
<header class="basemenu" id="header">
    <nav class="menu1">
        <nav class="base__logo_and_menu">
            <a class="base-logo" href="/"><img class="logo-main" src="../../static/img/logo.png" alt="Логотип"></a>
            <div class="base-menu-buttons">
                {% if request.user.is_authenticated %}
                    <div class="dropdown">
                      <a class="base_menu__a_guest_and_img" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                          <div class="base_menu__guest_name">{{ guest }}</div><img class="open-profile-button" src="{% static 'img/icons/icons8-login-66.png' %}" alt="Войти в кабинет">
                      </a>
                      <form class="dropdown-menu p-4" id="base_menu__container">
                          <div>{{ guest }}</div>
                          <div class="base_menu__lk_logout">
                              {% if request.user.slug %}
                                <a href="{% url 'app_profiler:account_detail' slug=request.user.slug %}">Личный кабинет</a>
                              {% else %}
                                <a href="{% url 'app_profiler:account_detail' id=request.user.id %}">Личный кабинет</a>
                              {% endif %}
                              <a href="{% url 'app_profiler:logout' %}">Выйти</a>
                          </div>
                          <ul class="base_menu__links_container">
                              {% if request.user.is_company %}
                                  <li class="base_menu__li_container">
                                      <a href="{% url 'app_profiler:company_detail' company_id=request.user.id %}">
                                          Кабинет арендодателя
                                      </a>
                                  </li>
                              {% endif %}
                                  <li class="base_menu__li_container"><a href="{% url 'app_profiler:account_reserves' slug=request.user.slug %}">Мои бронирования</a></li>
                          </ul>
                      </form>
                    </div>
                {% else %}
                    <div class="dropdown" id="login">
                            <a type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                <button type="button" class="btn btn-light">Войти</button>
                            </a>
                            <div class="dropdown-menu">
                                <form class="px-4 py-3" id="login-form" method="post">{% csrf_token %}
                                    <div class="mb-3">
                                        {{ auth_form.email }}
                                        {% if auth_form.errors %}
                                            {% for error in auth_form.email.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                    <div class="mb-3">
                                        {{ auth_form.password }}
                                    </div>
                                    <div class="mb-3">
                                        <div class="form-check" id="remember-me">
                                            <input type="checkbox" class="form-check-input" id="dropdownCheck">
                                            <label class="form-check-label" for="dropdownCheck">
                                                Запомнить меня
                                            </label>
                                        </div>
                                    </div>
                                    <button type="submit" id="base__login_form" name="submit-login-form" class="btn btn-success">Войти</button>
                                </form>
                                <div class="dropdown-divider"></div>
                                <form method="get" action="{% url 'app_profiler:register1' %}">
                                    <button class="dropdown-item" name="basic__register_button">Впервые у нас? <b>Зарегистрироваться</b></button>
                                </form>
                                <a class="dropdown-item" href="#">Забыли пароль?</a>
                            </div>
                    </div>
                {% endif %}
            </div>
        </nav>
        <nav class="base__main_menu">
            <a id="base__menu_buttons1" type="" href="{% url 'app_index:index' %}" class="btn btn-outline-light">Жилье</a>
<!--            <a id="base__menu_buttons2" type="" href="{% url 'app_auto:auto_index' %}" class="btn btn-outline-light">Авто</a>-->
        </nav>
        <nav class="base__main_menu">
            <div style="display: flex; flex-direction: column;">
                <div style="font-size: 2em; font-weight: bold; color: black;">
                    Бронируй, властвуй, отдыхай
                </div>
                <div style="font-size: 1.2em;">
                    Экономьте на отдыхе с нашим сервисом!
                </div>
            </div>
        </nav>
    </nav>
</header>

<body>
    {% block content %}{% endblock content %}
        <div id="pop_up" style="position: fixed; left: 50%; top: 50%;transform: translate(-50%, -50%); display: none; z-index: 100; padding: 5px;">
            <button id="close_pop_up_btn" class="btn-close" aria-label="Close"></button>
            <form class="register-container" method="post">{% csrf_token %}
                <div class="register-form-main-container">
                    <p class="register-form-container">
                        <p>{{ register_form.email }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.password1 }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.password2 }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.first_name }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.last_name }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.slug }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.phone }}</p>
                    <p class="register-form-container">
                        <p>{{ register_form.birthday }}</p>
                    <div class="form-check form-switch">
                        <p class="register-form-container">
                        <p>{{ register_form.is_company }}</p>
                        <label class="form-check-label" for="flexSwitchCheckDefault">Являюсь арендодателем</label>
                    </div>
                    <div class="form-check form-switch">
                        {{ register_form.is_active }}
                        <label class="form-check-label" for="flexSwitchCheckDefault">
                            Согласиться с <a style="color: blue;" href="{% url 'app_rules:rules' %}" target="_ blank">правилами сайта</a> и <a style="color: blue;" href="{% url 'app_rules:privacy_policy' %}" target="_ blank">Политикой конфиденциальности</a>
                        </label>
                    </div>
                </div>
                <button type="submit" name="save-register-form" class="btn btn-light" id="register-button">Зарегистрироваться</button>
            </form>
        </div>

    <script>
      $(function () {
        $("#id_birthday").datepicker({
          format:'dd.mm.yyyy',
          startDate:'today',
          autoHide:'True',
          autoPick:'True',
          language:'ru-RU',
        });
      });
    </script>

    <script>
        let pop_up   = document.getElementById('pop_up');
        let open_btn  = document.getElementById('open_pop_up');
        let close_btn = document.getElementById('close_pop_up_btn');

        open_btn.addEventListener('click',()=>{
            pop_up.style.display = 'block';
        })

        close_btn.addEventListener('click', ()=>{
            pop_up.style.display = 'none';
        })

    </script>

    <script>
        var myModal = document.getElementById('myModal')
        var myInput = document.getElementById('myInput')

        myModal.addEventListener('shown.bs.modal', function () {
          myInput.focus()
        })
    </script>

    <a href="#header"><img class="base__arrow_top" src="../../static/img/icons/free-icon-arrowhead-up-3838683.png"></a>
</body>
{% block footer %}
<footer class="base__footer_not_fixed">
    <div class="base__footer_container">
        <div class="base__copyright">
            <li class="base_menu__li_container"><a class="footer__links" href="{% url 'app_rules:our_values' %}">Наши ценности</a></li>
            <li class="base_menu__li_container"><a class="footer__links" href="{% url 'app_rules:rules' %}">Правила сайта</a></li>
            <li class="base_menu__li_container"><a class="footer__links" href="{% url 'app_rules:privacy_policy' %}">Политика конфиденциальности</a></li>
            <li class="base_menu__li_container"><a class="footer__links" href="" data-bs-toggle="modal" data-bs-target="#staticBackdrop5">Контакты</a></li>
        </div>
    </div>

    <!-- Модальное окно управления промо-акциями -->
    <div class="modal fade" id="staticBackdrop5" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel2" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel5">Контакты</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body" id="contacts_popup">
              <div>Телефон для справок: +7 (938) 416-66-72</div>
              <div>Эл. почта: biglov.info@yandex.ru</div>
          </div>
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>
</footer>
{% endblock footer %}
</html>

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html class="index__html" lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>{% block title %}Biglov | Официальный сайт | Снять квартиру, забронировать отель, авто{% endblock title %}</title>
    <link href="{% static 'css/reset.css' %}" type="text/css" rel="reset">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/stylesheet.css' %}" type="text/css" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <script src="../../static/js/datepicker.ru-RU.js"></script>

</head>
{% block content %}
<body class="index__body">

<!--    <div class="index-conteiner">-->
<!--        <div class="index-main-text">-->
<!--            <h2 class="index-h2-text">Бронируй, властвуй, отдыхай!</h2>-->
<!--            <div class="index-conteiner-h3-img">-->
<!--                <img class="just-chill-index" src="{% static 'img/just-chill.png' %}" alt="JUST_CHILL">-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <form class="search-form2" action="{% url 'app_premises:realty_list' %}" method="get">
        <input name="q" type="text" class="form-control" id="search-form" placeholder="Куда отправимся?" autocomplete="off">
        <div class="date-picker-index" id="base-search">
            {{ reserve_form.check_in }}
            {{ reserve_form.check_out }}
        </div>

        <script>
          $(function () {
            $("#main_search_in").datepicker({
              format:'dd.mm.yyyy',
              startDate:'today',
              autoHide:'True',
              autoPick:'True',
              language:'ru-RU',
            });
          });
        </script>

        <script>
          $(function () {
            $("#main_search_out").datepicker({
              format:'dd.mm.yyyy',
              startDate: 'today',
              autoHide:'True',
              language:'ru-RU',
            });
          });
        </script>
        <button name="search" class="btn btn-info" id="base-search-button">Проверить цены</button>
    </form>

    <div class="index__top_directions">
        <div class="index__top_title_container">
            <h4 class="index__top_h4_text">Выбор посетителей</h4>
            <img class="index__top_help_img" id="index__top_help" src="{% static 'img/icons/free-icon-information-906794.png' %}">
            <div class="index__top_help_show" style="display: none;">
                <div>Топ просматриваемых вариантов размещения</div>
            </div>
        </div>
        <div class="index__top_content_container">
            {% for object in index_realty_list %}
                <div class="index__top_content">
                    <a class="index__top_link_style" href="{% url 'app_premises:realty_detail' slug=object.slug %}">
                        <img class="index__top_img" src="../../media/{{ object.camp_photos.all.0.photo }}">
                        <div class="index__top_camp_title">{{ object }}</div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="index__top_directions">
        <div class="index__top_title_container">
            <h4 class="index__top_h4_text">Новые направления</h4>
        </div>

        <div class="index__top_content_container">
            <div class="index__top_content">
                <a class="index__top_link_style" href="#">
                    <img class="index__top_img" src="https://pibig.info/uploads/posts/2021-05/1622398817_26-pibig_info-p-priroda-utrom-more-priroda-krasivo-foto-26.jpg">
                    <div class="index__top_camp_title">Мезмай</div>
                </a>
            </div>

        </div>
    </div>

    <div class="index__top_directions">
        <div class="index__top_title_container">
            <h4 class="index__top_h4_text">Топовые направления</h4>
        </div>

        <div class="index__top_content_container">
            <div class="index__top_content">
                <a class="index__top_link_style" href="#">
                    <img class="index__top_img" src="https://img-fotki.yandex.ru/get/901683/13385546.81/0_b8a75_a0368965_orig">
                    <div class="index__top_directions_name">
                        Мезмай
                        <img src="{% static 'img/icons/free-icon-russia-197408.png' %}">
                    </div>
                </a>
            </div>

        </div>
    </div>

    <script>
        var x = document.querySelector('.index__top_help_img');
        var y =  document.querySelector('.index__top_help_show');
        x.onmouseover = function () {
            y.style.display = 'block';
        };
        x.onmouseout = function () {
            y.style.display = 'none';
        };
    </script>

</body>
{% endblock %}

</html>