app_auto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import auto_index_page
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'app_auto'

urlpatterns = [
    path('', auto_index_page, name='auto_index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_premises/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path
from .views import camp_list, RealtyDetailView, ReservationFormView, RealtyEditFromView, permission_denied, \
    favorite, add_comment, flat_list, LongTermRealtyDetailView, \
    LonTermRealtyEditFromView, lt_favorite, RegisterObject, create_camp_object_step1, \
    create_camp_object_step2, create_camp_object_step3, create_camp_object_step4, create_camp_object_step5, \
    create_camp_object_step6, create_camp_object_step7, create_camp_object_step8, create_flat_object_step1, \
    create_flat_object_step2, create_flat_object_step3, create_flat_object_step4, create_flat_object_step5, \
    create_flat_object_step6, create_flat_object_step7, create_flat_object_step8

app_name = 'app_premises'

urlpatterns = [
    #  Camp objects block
    path('hotels', camp_list, name='realty_list'),
    path('hotel/<slug:slug>/', RealtyDetailView.as_view(), name='realty_detail'),
    path('hotel/<slug:slug>/edit', RealtyEditFromView.as_view(), name='realty_edit'),
    path('create-camp/1', create_camp_object_step1, name='create_camp1'),
    path('create-camp/2', create_camp_object_step2, name='create_camp2'),
    path('create-camp/3', create_camp_object_step3, name='create_camp3'),
    path('create-camp/4', create_camp_object_step4, name='create_camp4'),
    path('create-camp/5', create_camp_object_step5, name='create_camp5'),
    path('create-camp/6', create_camp_object_step6, name='create_camp6'),
    path('create-camp/7', create_camp_object_step7, name='create_camp7'),
    path('create-camp/8', create_camp_object_step8, name='create_camp8'),
    #  Error pages
    path('error/403', permission_denied, name='403'),
    #  Long term objects block
    path('long/', flat_list, name='flat_list'),
    path('long/<int:pk>/', LongTermRealtyDetailView.as_view(), name='lt_realty_detail'),
    path('long/<int:pk>/edit', LonTermRealtyEditFromView.as_view(), name='lt_realty_edit'),
    path('create-long-term/1', create_flat_object_step1, name='create_flat1'),
    path('create-long-term/2', create_flat_object_step2, name='create_flat2'),
    path('create-long-term/3', create_flat_object_step3, name='create_flat3'),
    path('create-long-term/4', create_flat_object_step4, name='create_flat4'),
    path('create-long-term/5', create_flat_object_step5, name='create_flat5'),
    path('create-long-term/6', create_flat_object_step6, name='create_flat6'),
    path('create-long-term/7', create_flat_object_step7, name='create_flat7'),
    path('create-long-term/8', create_flat_object_step8, name='create_flat8'),
    #  Register realty objects main page
    path('register-object/', RegisterObject.as_view(), name='register_object'),
    #  Reservation page
    path('reservation', ReservationFormView.as_view(), name='reservation'),
    #  AJAX pages
    re_path(r'^favorite/$', favorite, name='favorite'),
    re_path(r'^add_comment/$', add_comment, name='add_comment'),
    re_path(r'^lt_favorite/$', lt_favorite, name='lt_favorite'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_rules/urls.py
from django.conf import settings
from django.urls import path
from .views import our_values_page, rules_page, privacy_policy_page
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app_rules'

urlpatterns = [
    path('values', our_values_page, name='our_values'),
    path('regulations', rules_page, name='rules'),
    path('privacy', privacy_policy_page, name='privacy_policy'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

"""Импорт библиотек для Swagger"""
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_version = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_profiler.urls')),
    path('rules/', include('app_rules.urls')),
    path('auto/', include('app_auto.urls')),
    path('rent/', include('app_premises.urls')),
    path('', include('app_index.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_auto/models.py
from django.db import models

# Create your models here.

app_premises/forms.py
import datetime
from django import forms
from .models import Camp, Reservation, Photos, Flat
from .services.base_services import IN_HOTEL_OPTIONS, IN_ROOM_OPTIONS, FURNITURE, TECHNIQUE


_FILTER_TYPE = [
    ('p', 'По популярности'),
    ('i', 'Сначала дешевле'),
    ('x', 'Сначала дороже'),
]

_REALTY_TYPE = [
    ('h', 'Отель'),
    ('c', 'Хостел'),
    ('a', 'Апартаменты'),
    ('ah', 'Апарт-отель'),
    ('gh', 'Гостевой дом'),
    ('k', 'Коттедж'),
    ('v', 'Вилла'),
    ('kp', 'Кемпинг'),
    ('gp', 'Глэмпинг'),
]

_FOOD_OPTIONS = [
    ('a', 'Завтрак включён'),
    ('b', 'Завтрак + обед или ужин включены'),
    ('c', 'Завтрак, обед и ужин включены'),
    ('d', 'Всё включено'),
    ('e', 'Питание не включено'),
]


today = datetime.date.today()
tomorrow = today + datetime.timedelta(days=1)

""" Форма для создания объекта недвижимости типа 'Кемпинг' """


class HolidayHouseForm(forms.ModelForm):
    class Meta:
        model = Camp
        fields = '__all__'
        exclude = ['created_at', 'realty_book_count', 'is_favorites', 'views_count']

    def __init__(self, *args, **kwargs):
        super(HolidayHouseForm, self).__init__(*args, **kwargs)
        """Работа с классами формы"""
        self.fields['realty_name'].widget.attrs['class'] = 'create-realty-input'
        self.fields['realty_country'].widget.attrs['class'] = 'create-realty-input'
        self.fields['realty_region'].widget.attrs['class'] = 'create-realty-input'
        self.fields['realty_city'].widget.attrs['class'] = 'create-realty-input'
        self.fields['realty_address'].widget.attrs['class'] = 'create-realty-input'
        self.fields['realty_to_city'].widget.attrs['class'] = 'create-realty-input'
        self.fields['count_of_persons'].widget.attrs['class'] = 'create-realty-input-short'
        self.fields['realty_price'].widget.attrs['class'] = 'create-realty-input-short'
        self.fields['realty_area'].widget.attrs['class'] = 'create-realty-input-short'
        self.fields['region_center'].widget.attrs['class'] = 'create-realty-input-short'
        self.fields['arriving_time'].widget.attrs['class'] = 'create-realty-input'
        self.fields['departure_time'].widget.attrs['class'] = 'create-realty-input'
        # self.fields['company'] = forms.ModelChoiceField(
        #     required=True,
        #     queryset=ManagerProfile.objects.filter(referring_user=1))


class CreateHolidayHouseForm(forms.ModelForm):
    class Meta:
        model = Camp
        fields = '__all__'
        exclude = ['created_at', 'realty_book_count', 'is_favorites', 'views_count', 'slug']

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm, self).__init__(*args, **kwargs)
        """Работа с классами формы"""

        self.fields['realty_country'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['realty_region'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['realty_city'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['realty_address'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['realty_to_city'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['count_of_persons'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['realty_price'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['realty_area'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['region_center'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['arriving_time'].widget.attrs['class'] = 'hh_realty_create__input'
        self.fields['departure_time'].widget.attrs['class'] = 'hh_realty_create__input'

        self.fields['realty_name'].widget.attrs['class'] = 'form-control'
        self.fields['realty_name'].widget.attrs['required'] = True
        self.fields['realty_name'].widget.attrs['placeholder'] = 'Мезмайская пустошь'


class CreateHolidayHouseForm1(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('realty_name', 'company')

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm1, self).__init__(*args, **kwargs)
        """Работа с классами формы"""

        self.fields['realty_name'].widget.attrs['class'] = 'form-control'
        self.fields['realty_name'].widget.attrs['required'] = True
        self.fields['realty_name'].widget.attrs['placeholder'] = 'Мезмайская пустошь'


class CreateHolidayHouseForm2(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('realty_country', 'realty_city', 'realty_address', 'ind')

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm2, self).__init__(*args, **kwargs)
        """Работа с классами формы"""

        self.fields['ind'].widget.attrs['class'] = 'form-control'
        self.fields['ind'].widget.attrs['required'] = True
        self.fields['ind'].widget.attrs['placeholder'] = '350000'

        self.fields['realty_country'].widget.attrs['class'] = 'form-control'
        self.fields['realty_country'].widget.attrs['required'] = True
        self.fields['realty_country'].widget.attrs['placeholder'] = 'Россия'

        self.fields['realty_city'].widget.attrs['class'] = 'form-control'
        self.fields['realty_city'].widget.attrs['required'] = True
        self.fields['realty_city'].widget.attrs['placeholder'] = 'Москва'

        self.fields['realty_address'].widget.attrs['class'] = 'form-control'
        self.fields['realty_address'].widget.attrs['required'] = True
        self.fields['realty_address'].widget.attrs['placeholder'] = 'пр. Писателя Знаменского, 6'


class CreateHolidayHouseForm3(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('count_of_persons', 'realty_area', 'realty_type', 'book_cancel', 'pay_type', 'food_options', 'stars')

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm3, self).__init__(*args, **kwargs)
        """Работа с классами формы"""

        self.fields['count_of_persons'].widget.attrs['class'] = 'form-control'
        self.fields['count_of_persons'].widget.attrs['required'] = True

        self.fields['realty_type'].widget.attrs['class'] = 'form-control'
        self.fields['realty_type'].widget.attrs['required'] = True

        self.fields['realty_area'].widget.attrs['class'] = 'form-control'
        self.fields['realty_area'].widget.attrs['required'] = True

        self.fields['stars'].widget.attrs['class'] = 'form-control'
        self.fields['stars'].widget.attrs['required'] = True

        self.fields['book_cancel'].widget.attrs['required'] = True
        self.fields['book_cancel'].widget.attrs['id'] = 'book_cancel_create_camp'
        self.fields['book_cancel'].widget.attrs['class'] = 'form-select'
        self.fields['pay_type'].widget.attrs['required'] = True
        self.fields['pay_type'].widget.attrs['id'] = 'pay_type_create_camp'
        self.fields['pay_type'].widget.attrs['class'] = 'form-select'
        self.fields['food_options'].widget.attrs['required'] = True
        self.fields['food_options'].widget.attrs['id'] = 'food_options_create_camp'
        self.fields['food_options'].widget.attrs['class'] = 'form-select'


class CreateHolidayHouseForm4(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('options',)

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm4, self).__init__(*args, **kwargs)
        """Работа с классами формы"""

        self.fields['options'].widget.attrs['required'] = True


class CreateHolidayHouseForm5(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('arriving_time', 'departure_time', 'arriving_time_to', 'departure_time_to')

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm5, self).__init__(*args, **kwargs)
        """Работа с классами формы"""

        self.fields['arriving_time'].widget.attrs['class'] = 'form-control'
        self.fields['departure_time'].widget.attrs['class'] = 'form-control'
        self.fields['arriving_time_to'].widget.attrs['class'] = 'form-control'
        self.fields['departure_time_to'].widget.attrs['class'] = 'form-control'


class CreateHolidayHouseForm6(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('full_description',)

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm6, self).__init__(*args, **kwargs)
        """ Работа с классами формы """


class CreateHolidayHouseForm7(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ('realty_price',)

    def __init__(self, *args, **kwargs):
        super(CreateHolidayHouseForm7, self).__init__(*args, **kwargs)
        """ Работа с классами формы """
        self.fields['realty_price'].widget.attrs['class'] = 'form-control'


""" Формы связанные с резервированием """


class ReservationForm(forms.ModelForm):
    """ Форма резервирования объекта """

    class Meta:
        model = Reservation
        fields = ('check_in', 'check_out', 'total_sum')
        exclude = ['realty', 'guest', 'is_booked']

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        self.fields['total_sum'].widget.attrs['readonly'] = True
        self.fields['check_in'].widget.attrs['placeholder'] = today.strftime("%d.%m.%Y")
        self.fields['check_out'].widget.attrs['placeholder'] = tomorrow.strftime("%d.%m.%Y")
        self.fields['check_in'].widget.attrs['autocomplete'] = 'Off'
        self.fields['check_out'].widget.attrs['autocomplete'] = 'Off'


class ReservationListSearchForm(forms.Form):
    """ Форма резервирования для вывода date picker на страницу списка бъектов """

    check_in = forms.DateField(required=False)
    check_out = forms.DateField(required=False)

    def __init__(self, *args, **kwargs):
        super(ReservationListSearchForm, self).__init__(*args, **kwargs)

app_auto/views.py
from django.shortcuts import render
from app_profiler.models import CustomUser

"""Главная страница"""


def auto_index_page(request):
    if request.user.is_authenticated:
        if request.user.is_company:
            user_slug = request.user.slug
            current_company = CustomUser.objects.get(user=request.user.id)
            company_slug = current_company.slug
            return render(request, 'app_auto/auto_index.html', {'user_slug': user_slug, 'company_slug': company_slug})
        else:
            user_slug = request.user.slug
            company_slug = None
            return render(request, 'app_auto/auto_index.html', {'user_slug': user_slug, 'company_slug': company_slug})
    else:
        user_slug = None
        company_slug = None
        return render(request, 'app_auto/auto_index.html', {'user_slug': user_slug, 'company_slug': company_slug})

templates/app_auto/auto_index.html
{% extends "base.html" %}

{% load static %}

<head>
    <title>{% block title %}Biglov | Официальный сайт | Снять квартиру, забронировать отель, авто{% endblock title %}</title>
</head>
{% block content %}
<body class="index__body">

    <form class="car__search_form_2" action="{% url 'app_premises:realty_list' %}" method="get">
        <div class="auto__main_text_container">
            <h3 class="auto__h3_text">Аренда автомобилей для любой поездки</h3>
        </div>
        <div class="auto__search_form_container">
            <menu class="search-form-input">
                <div class="container2">
                    <div class="row height d-flex justify-content-center align-items-center">
                        <div class="col-md-8" id="search-form-input">
                            <div class="search2">
                                <i class="fa fa-search"></i>
                                <input name="q" type="text" class="form-control" id="search-form" placeholder="Место получения авто" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="index-search-button-container2">
                    <button name="search" class="btn btn-info" id="base-search-button">Проверить цены</button>
                </div>
            </menu>
            <menu class="search-form2-datepicker">
                <div class="date-picker-index" id="base-search">
                    {{ reserve_form.check_in }} -
                    {{ reserve_form.check_out }}
                </div>

                <script>
                  $(function () {
                    $("#id_check_in").datepicker({
                      format:'dd.mm.yyyy',
                      startDate:'today',
                      autoHide:'True',
                      autoPick:'True',
                      language:'ru-RU',
                    });
                  });
                </script>

                <script>
                  $(function () {
                    $("#id_check_out").datepicker({
                      format:'dd.mm.yyyy',
                      startDate: 'today',
                      autoHide:'True',
                      language:'ru-RU',
                    });
                  });
                </script>
            </menu>
        </div>
    </form>

    <div class="auto__avd_place_container">
        <h3 class="auto__adv_place_h3_text">Популярные прокатные компании</h3>
        <div class="auto__adv_container">

        </div>
    </div>

    <div class="index__adv_long_term">
        <div class="index__adv_main_container">
            <div class="index__adv_text">
                <div>
                    Планируете переезд?
                    <div class="index__adv_text_sub">С нами это сделать гораздо проще! Выбери интересующий вариант и забронируй его на <b style="color: #0f90e4">Biglov.ru</b></div>
                </div>
                <a id="base__menu_buttons1" type="" href="{% url 'app_premises:lt_realty_list' %}" class="btn btn-success">Найти жилье на длительный срок</a>
            </div>
        </div>
        <div class="index__adv_container_for_background">

        </div>
    </div>
</body>
{% endblock %}
{% block footer %}
<footer class="base__footer_not_fixed">
    <div class="base__footer_container">
        <a class="base__logo_footer" href="/"><img class="logo-main_footer" src="../../static/img/logo.png" alt="Логотип"></a>
    </div>
    <div class="base__footer">
        <div class="base__copyright">
            <li class="base_menu__li_container"><a href="{% url 'app_rules:our_values' %}">Наши ценности</a></li>
            <li class="base_menu__li_container"><a href="{% url 'app_rules:rules' %}">Правила сайта</a></li>
            <li class="base_menu__li_container"><a href="{% url 'app_rules:privacy_policy' %}">Политика конфиденциальности</a></li>
            <li class="base_menu__li_container"><a href="" data-bs-toggle="modal" data-bs-target="#staticBackdrop5">Контакты</a></li>
        </div>
    </div>

    <!-- Модальное окно управления промо-акциями -->
    <div class="modal fade" id="staticBackdrop5" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel2" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel5">Контакты</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body">
              <div>Телефон для справок: +7 (938) 416-66-72</div>
              <div>Эл. почта: biglov.info@yandex.ru</div>
          </div>
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>
</footer>
{% endblock footer %}
</html>