app_premises/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, re_path
from .views import camp_list, RealtyDetailView, ReservationFormView, RealtyEditFromView, permission_denied, \
    favorite, add_comment, flat_list, LongTermRealtyDetailView, \
    LonTermRealtyEditFromView, lt_favorite, RegisterObject, create_camp_object_step1, \
    create_camp_object_step2, create_camp_object_step3, create_camp_object_step4, create_camp_object_step5, \
    create_camp_object_step6, create_camp_object_step7, create_camp_object_step8, create_flat_object_step1, \
    create_flat_object_step2, create_flat_object_step3, create_flat_object_step4, create_flat_object_step5, \
    create_flat_object_step6, create_flat_object_step7, create_flat_object_step8

app_name = 'app_premises'

urlpatterns = [
    #  Camp objects block
    path('hotels', camp_list, name='realty_list'),
    path('hotel/<slug:slug>/', RealtyDetailView.as_view(), name='realty_detail'),
    path('hotel/<slug:slug>/edit', RealtyEditFromView.as_view(), name='realty_edit'),
    path('create-camp/1', create_camp_object_step1, name='create_camp1'),
    path('create-camp/2', create_camp_object_step2, name='create_camp2'),
    path('create-camp/3', create_camp_object_step3, name='create_camp3'),
    path('create-camp/4', create_camp_object_step4, name='create_camp4'),
    path('create-camp/5', create_camp_object_step5, name='create_camp5'),
    path('create-camp/6', create_camp_object_step6, name='create_camp6'),
    path('create-camp/7', create_camp_object_step7, name='create_camp7'),
    path('create-camp/8', create_camp_object_step8, name='create_camp8'),
    #  Error pages
    path('error/403', permission_denied, name='403'),
    #  Long term objects block
    path('long/', flat_list, name='flat_list'),
    path('long/<int:pk>/', LongTermRealtyDetailView.as_view(), name='lt_realty_detail'),
    path('long/<int:pk>/edit', LonTermRealtyEditFromView.as_view(), name='lt_realty_edit'),
    path('create-long-term/1', create_flat_object_step1, name='create_flat1'),
    path('create-long-term/2', create_flat_object_step2, name='create_flat2'),
    path('create-long-term/3', create_flat_object_step3, name='create_flat3'),
    path('create-long-term/4', create_flat_object_step4, name='create_flat4'),
    path('create-long-term/5', create_flat_object_step5, name='create_flat5'),
    path('create-long-term/6', create_flat_object_step6, name='create_flat6'),
    path('create-long-term/7', create_flat_object_step7, name='create_flat7'),
    path('create-long-term/8', create_flat_object_step8, name='create_flat8'),
    #  Register realty objects main page
    path('register-object/', RegisterObject.as_view(), name='register_object'),
    #  Reservation page
    path('reservation', ReservationFormView.as_view(), name='reservation'),
    #  AJAX pages
    re_path(r'^favorite/$', favorite, name='favorite'),
    re_path(r'^add_comment/$', add_comment, name='add_comment'),
    re_path(r'^lt_favorite/$', lt_favorite, name='lt_favorite'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_profiler/urls.py
from django.conf import settings
from django.urls import path
from .views import AnotherLogoutView, AccountEditFromView, AccountReservationListView, CompanyEditFromView, \
    register_step1, register_step2, register_step3
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app_profiler'

urlpatterns = [
    path('logout/', AnotherLogoutView.as_view(), name='logout'),
    path('account/<slug:slug>/', AccountEditFromView.as_view(), name='account_detail'),
    path('account/<slug:slug>/reserve', AccountReservationListView.as_view(), name='account_reserves'),
    path('company/<int:company_id>/', CompanyEditFromView.as_view(), name='company_detail'),
    #  Шаги регистрации
    path('register/1', register_step1, name='register1'),
    path('register/2', register_step2, name='register2'),
    path('register/3', register_step3, name='register3'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_rules/urls.py
from django.conf import settings
from django.urls import path
from .views import our_values_page, rules_page, privacy_policy_page
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app_rules'

urlpatterns = [
    path('values', our_values_page, name='our_values'),
    path('regulations', rules_page, name='rules'),
    path('privacy', privacy_policy_page, name='privacy_policy'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

"""Импорт библиотек для Swagger"""
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

api_version = 'api/v1/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_profiler.urls')),
    path('rules/', include('app_rules.urls')),
    path('auto/', include('app_auto.urls')),
    path('rent/', include('app_premises.urls')),
    path('', include('app_index.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app_profiler/models.py
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from .managers import UserManager
from pytils.translit import slugify
from django.urls import reverse


_LOYALTY_SYSTEM = [
    ('d', 'Джун'),
    ('D', 'Джун+'),
    ('m', 'Мид'),
    ('M', 'Мид+'),
    ('s', 'Синьор'),
]

_GENDER = [
    ('m', 'Мужской'),
    ('w', 'Женский'),
]

_MANAGER_TYPE = [
    ('c', 'Организация'),
    ('p', 'Самозанятый'),
]

_NDS = [
    ('y', 'с НДС'),
    ('n', 'без НДС')
]

phone_regex = RegexValidator(regex=r'^(\+\d{7})?,?\s?\d{8,13}', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    slug = models.SlugField(max_length=30, unique=True, verbose_name='Имя для slug')
    first_name = models.CharField(max_length=30, blank=True, verbose_name='Имя')
    last_name = models.CharField(max_length=30, blank=True, verbose_name='Фамилия')
    phone = models.CharField(max_length=12, blank=True, default='', help_text='Номер телефона')
    telegram = models.CharField(max_length=30, blank=True, verbose_name='Телеграмм')

    birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    gender = models.CharField(max_length=1, choices=_GENDER, default='m', blank=True, verbose_name='Пол')
    book_count = models.PositiveIntegerField(default=0, verbose_name='Бронирований')
    status = models.CharField(max_length=1, choices=_LOYALTY_SYSTEM, default='d', verbose_name='Статус клиента')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')
    is_active = models.BooleanField(default=False, verbose_name='Активен')
    is_company = models.BooleanField(default=False, verbose_name='Компания')
    is_staff = models.BooleanField(default=False, verbose_name='Статус персонала')
    is_superuser = models.BooleanField(default=False, verbose_name='Статус Администратора')

    """ Часть модели, относящаяся к данным компании """

    type = models.CharField(max_length=1, blank=True, choices=_MANAGER_TYPE, verbose_name='Форма управления')
    nds = models.CharField(max_length=1, blank=True, choices=_NDS, verbose_name='НДС')
    full_company_name = models.CharField(max_length=100, blank=True, verbose_name='Полное наименование')
    short_company_name = models.CharField(max_length=100, blank=True, verbose_name='Сокращенное наименование')
    legal_address = models.CharField(max_length=250, blank=True, verbose_name='Юридический адрес')
    actual_address = models.CharField(max_length=250, blank=True, verbose_name='Фактический адрес')
    inn = models.CharField(max_length=10, blank=True, verbose_name='ИНН')
    kpp = models.CharField(max_length=9, blank=True, verbose_name='КПП')
    ogrn = models.CharField(max_length=13, blank=True, verbose_name='ОГРН')
    bank_account = models.CharField(max_length=22, blank=True, verbose_name='Рассчётный счёт')
    bank_name = models.CharField(max_length=200, blank=True, verbose_name='Наименование банка')
    kor_account = models.CharField(max_length=22, blank=True, verbose_name='Корреспондентский счёт')
    bic = models.CharField(max_length=9, blank=True, verbose_name='БИК')
    middle_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Отчество')
    passport_series = models.CharField(max_length=4, blank=True, null=True, verbose_name='Серия паспорта')
    passport_number = models.CharField(max_length=6, blank=True, null=True, verbose_name='Номер паспорта')
    passport_who = models.CharField(max_length=100, null=True, blank=True, verbose_name='Кем выдан')
    passport_code = models.CharField(max_length=10, null=True, blank=True, verbose_name='Код подразделения')
    passport_date = models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        # db_table = 'accounts_db'
        ordering = ['created_at']
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def get_absolute_url(self):
        return reverse("account_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = slugify(self.slug)
        return super().save(*args, **kwargs)

    def get_full_name(self):
        """Возвращает полное имя пользователя."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Возвращает имя пользователя."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Отправка письма на почту пользователю."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

templates/app_profiler/login.html
<!DOCTYPE html>
{% extends "base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Вход{% endblock title %}</title>
</head>
{% block content%}
<body>
    <section>
        <form method="post">
                {% csrf_token %}
                {{ auth_form.as_p }}
            <p>
                <button class="login" type="submit">Войти</button>
                или
                <a class="register" href="/register">Зарегистрироваться</a>
            </p>
        </form>
    </section>
</body>
{% endblock content %}
</html>

templates/app_profiler/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выйти из учтной записи</title>
</head>
<body>
    <h2>Выйти из учётной записи</h2>
    Вы успешно вышли из своей учётной записи!
</body>
</html>

templates/app_profiler/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <link rel="reset" href="static/css/reset.css">
    <link rel="stylesheet" href="static/css/stylesheet.css">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
        <a href="/">Назад</a>
    </form>
</body>
</html>

templates/app_profiler/register1.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Biglov.ru | Регистрация объекта{%endblock title %}</title>
    <link type="text/css" rel="reset" href="../../static/css/reset.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link type="text/css" rel="stylesheet" href="../../static/css/style.css">
    <link type="text/css" rel="stylesheet" href="../../static/css/stylesheet.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>
{% block content %}
    <div class="register_user__main_container" id="camp_step1_container">
      <form class="create-realty-form" method="post" enctype="multipart/form-data">{% csrf_token %}
            <h2 class="register_camp__h2_text">Регистрация пользователя</h2>
                    <div style="width: 100%; margin-bottom: 10px;">
                        <div style="text-align: left; color: black; font-weight: 600;">Логин:</div>
                        {{ register_form.email }}
                        {% if register_form.errors %}
                            {% for error in register_form.email.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div style="width: 100%; margin-bottom: 10px;">
                        <div style="text-align: left; color: black; font-weight: 600;">Пароль:</div>
                        {{ register_form.password1 }}
                        {% if register_form.errors %}
                            {% for error in register_form.password1.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div style="width: 100%; margin-bottom: 10px;">
                        <div style="text-align: left; color: black; font-weight: 600;">Подтвердите пароль:</div>
                        {{ register_form.password2 }}
                        {% if register_form.errors %}
                            {% for error in register_form.password2.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
          <button type="submit" class="btn btn-success register_camp__next_button" id="camp_step1">Дальше</button>
      </form>

      <div class="register_camp__info_block_container">
          <div class="register_camp__info_block">
              <h5>Выбор данных для регистрации</h5>
              <ul>
                  <li>Используйте только Вашу почту, доступ к которой нет ни у кого кроме Вас.</li>
                  <li>
                      Почта должна быть активной, так как именно с её помощью Вы сможете авторизоваться на сайте и вся
                      информация по взаимодействию с сайтом Biglov.ru направляется только на данную почту.
                  </li>
                  <li>
                      Придумайте надёжный пароль и никому его не сообщайте. Старайтесь не хранить его в смартфоне, в
                      файле на компьютере или на бумаге.
                  </li>
              </ul>
          </div>
          <div class="register_camp__info_block">
              <h5>Зачем нужен аккаунт?</h5>
              <div>
                  Для того чтобы просматривать предложения на сайте регистрация не требуется, но если Вы захотите
                  забронировать объект у наших партнёров, то Вам нужен аккаунт так как данные аккаунта используются для
                  подтверждения бронирования и связи с Вами в случае необходимости.
              </div>
          </div>
          <div class="register_camp__info_block">
              <h5>Защищены ли мои персональные данные?</h5>
              <div>
                  Защита персональных данных наших пользователей - самая приоритетная наша задача!
                  <br></br>
                  На сайте не предусмотрено страниц пользователей для открытого доступа, поэтому никто кроме Вас не
                  может зайти и посмотреть Ваши данные, если Вы сами не передадите данные для входа на сайт другому
                  человеку.
                  <br></br>
                  Мы передадим Ваши контакты сотрудникам объекта, который Вы забронируете. В контактные данные войдут:
                  адрес электронной почты, номер телефона и ссылка на телеграм для удобства коммуникации.
              </div>
          </div>
          <div class="register_camp__info_block">
              <h5 style="color: black; font-weight: 600;">Важная информация!</h5>
              <div>
                  Продолжая регистрацию Вы даёте своё согласие на обработку персональных данных, а так же соглашаетесь с
                  <a href="{% url 'app_rules:rules' %}">Правилами сайта</a> и
                  <a href="{% url 'app_rules:privacy_policy' %}">Политикой конфиденциальности</a>.
              </div>
          </div>
      </div>
    </div>
{% endblock %}
</body>

</html>

templates/app_profiler/user_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
<html lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ current_user.first_name }} {{ current_user.last_name }}{% endblock title %}</title>
    <link type="text/css" rel="reset" href="../../static/css/reset.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../../static/css/style.css">
    <link type="text/css" rel="stylesheet" href="../../static/css/stylesheet.css">

</head>
<body>
    {% block content %}
<!--    <div style="display: block; height: 50px;"></div>-->
    <div class="user_detail__main_container">
        <div class="user_detail__forms_container">
            <form class="account__form_container" method="post">{% csrf_token %}
                <div class="account__div_container">
                    <h4>Персональные данные</h4>
                    <div class="account__name_container">
                        {{ account_form.status.as_hidden }}
                        {{ account_form.created_at.as_hidden }}
                        {{ account_form.is_active.as_hidden }}
                        {{ account_form.is_company.as_hidden }}
                        {{ account_form.as_staff.as_hidden }}
                        {{ account_form.is_superuser.as_hidden }}
                        {{ account_form.book_count.as_hidden }}
                        {{ account_form.password.as_hidden }}
                        {{ account_form.slug.as_hidden }}
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Ваше имя:</label>
                            {{ account_form.first_name }}
                        </div>
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Ваша фамилия:</label>
                            {{ account_form.last_name }}
                        </div>
                    </div>

                    <div class="account__birth_and_gender_container">
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Дата рождения:</label>
                            {{ account_form.birthday }} {{ account_form.birthday.errors }}
                        </div>
                        <div style="width: 45%;">
                            <label class="user_detail__label_font_size" for="id_gender">Пол:</label>
                            <select class="edit-account-input" name="gender" id="id_gender" aria-label="Пример выбора по умолчанию">
                            {% for gender in account_form.gender %}
                                {{ gender }}
                            {% endfor %}
                        </select>
                        </div>
                    </div>

                    <div class="account__phone_and_email_container">
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Номер телефона:</label>
                            {{ account_form.phone }}
                        </div>
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Электронная почта:</label>
                            {{ account_form.email }}
                        </div>
                    </div>
                    <div class="account__phone_and_email_container">
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Телеграмм:</label>
                            <span class="input-group-text" id="inputGroupPrepend">@{{ account_form.telegram }}</span>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-success" name="account__save_form" style="margin-top: 10px;">Сохранить</button>
                </div>
            </form>
            <form class="account__change_slug" method="post" action="{% url 'app_profiler:account_detail' slug=request.user.slug %}">{% csrf_token %}
                <div class="account__div_container">
                    <h4>Задать красивый адрес</h4>
                    <div class="account__slug_container">
                        {{ account_form.status.as_hidden }}
                        {{ account_form.created_at.as_hidden }}
                        {{ account_form.is_active.as_hidden }}
                        {{ account_form.is_company.as_hidden }}
                        {{ account_form.as_staff.as_hidden }}
                        {{ account_form.is_superuser.as_hidden }}
                        {{ account_form.book_count.as_hidden }}
                        {{ account_form.password.as_hidden }}
                        {{ account_form.first_name.as_hidden }}
                        {{ account_form.last_name.as_hidden }}
                        {{ account_form.phone.as_hidden }}
                        {{ account_form.email.as_hidden }}
                        {{ account_form.birthday.as_hidden }}
                        {{ account_form.slug }}
                    </div>
                    <button type="submit" class="btn btn-success" id="account__change_slug" name="account__change_slug">Сохранить</button>
                </div>
            </form>
            <form class="account__change_password" method="post" >{% csrf_token %}
                <div class="account__div_container">
                    <h4>Сменить пароль</h4>
                    <div class="account__name_container">
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Старый пароль:</label>
                            {{ change_password_form.old_password }}
                        </div>
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Новый пароль:</label>
                            {{ change_password_form.new_password1 }}
                        </div>
                        <div class="account__names">
                            <label class="user_detail__label_font_size">Подтвердите пароль:</label>
                            {{ change_password_form.new_password2 }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success" id="account__change_password" name="account__change_password_form">Сохранить</button>
                </div>
            </form>
        </div>
        <div class="user_detail__favorites_container">
            <h4 style="text-align: center;">Избранное</h4>
            <div class="user_detail__favorite_list_container">
                {% if favorite_list %}
                    {% for object in favorite_list %}
                        {% for element in object.camps.all %}
                            <div>

                                <a href="{% url 'app_premises:realty_detail' slug=element.slug %}"><img class="user_detail__favorite_list_img" src="../../media/{{ element.camp_photos.all.0.photo }}">{{ element }}</a>
                            </div>
                        {% endfor %}
                        {% for element in object.flats.all %}
                            <div>
                                <img class="user_detail__favorite_list_img" src="../../media/{{ element.flat_photos.all.0.photo }}">
                                <a href="{% url 'app_premises:lt_realty_detail' pk=element.id %}">{{ element }}</a>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
</body>

</html>